#!/bin/bash

########################分发文件##########################
param_count=$#
if((param_count==0));then
	echo "no args; 参数不能为空"
	#如果参数为空，直接退出
	exit;
fi

#判断是文件还是目录
param=$1
if [ -d $param ];then
cd $param
param=$(pwd)
fi

#获取basename
basename=`basename $param`
#获取basename所在的目录
pdir=$(cd $(dirname $param);pwd)

local_ip=$(ip addr | grep inet | grep .255 | cut -d '/' -f 1 | awk -F ' ' '{print $2}')

server_ips=$(grep server_ /etc/hosts | awk '{print $1}')
for server_ip in ${server_ips}
do
	echo "----------分发文件到${server_ip}----------"
	#如果是当前机器的ip, 则跳过
	if [ "${local_ip}"x = "${server_ip}"x ];then
		echo "----------本机不用分发，跳过-------------"
		continue
	fi
	
	#如果本身就是home/poles的，则无需移动
	echo "scp -r ${pdir}/${basename} poles@${server_ip}:/home/poles/"
	scp -r ${pdir}/${basename} poles@${server_ip}:/home/poles/

	if [ "${pdir}"x != "/home/poles"x ];then
		ssh poles@${server_ip} "sudo mv -f /home/poles/${basename} ${pdir}"
	fi
done
